---
title: "R Notebook"
output: html_notebook
---

```{r}
setwd("/Users/helending/Documents/BCB330/code/disease_tissues/melanoma")
library(miRNAmeConverter)
```

```{r}
# Download dataset
datafile <- "GSE89438_LMMEL_miRNA_counts_compiled.txt.gz"
if (!file.exists(datafile)) {
  datafile <- GEOquery::getGEOSuppFiles('GSE89438', makeDirectory = FALSE)
}

expr <- read.delim(datafile,header=TRUE,check.names=FALSE)
```

```{r}
copy_y <- expr[2:ncol(expr)]

# compare each expression value to thres
for(i in 1:nrow(copy_y)){
  for (j in 1:ncol(copy_y)){
    if (copy_y[i, j] >= 5){
      copy_y[i, j] <- 1
    } else{
      copy_y[i, j] <- 0
    }
  }
}

# sum the rows
copy_y <- cbind("SUM"=rowSums(copy_y), copy_y)
copy_y <- cbind("miR"=expr[,1], copy_y)
rownames(copy_y) <- 1:nrow(copy_y)
nrow(copy_y) # 2639
```
```{r}
nc = MiRNANameConverter()
known_miR <- checkMiRNAName(nc, as.character(copy_y$miR)) # all known miR
length(known_miR) # 2163
length(copy_y$miR) # 2177
```


```{r}
copy_y <- copy_y[, 1:2]
copy_y <- cbind(copy_y, "sample_num"=57)
colnames(copy_y)[2] <- "melanoma"

`%notin%` <- Negate(`%in%`)
ind_novel <- which(copy_y$miR %notin% known_miR)
length(ind_novel) # 14
novel <- copy_y[ind_novel, ]
rownames(novel) <- 1:nrow(novel)
# save
write.table(novel, file="/Users/helending/Documents/BCB330/mirDIP/expr_data_novel/final_novel_melanoma.csv")

known <- copy_y[-which(copy_y$miR %in% novel$miR),]
write.table(known, file="/Users/helending/Documents/BCB330/mirDIP/expr_data_known/final_known_melanoma.csv")
```



