---
title: "R Notebook"
output: html_notebook
---

```{r}
setwd("/Users/helending/Documents/BCB330/code/normal_tissues/adipose_tissue")
library(readxl)
```


```{r}
# Download dataset
datafile <- "GSE45159_METSIM_miRNA_Weighted_Counts.txt.gz"
if (!file.exists(datafile)) {
  datafile <- GEOquery::getGEOSuppFiles('GSE45159', makeDirectory = FALSE)
}

expr <- read.table(datafile, stringsAsFactors = FALSE)
colnames(expr) <- as.character(expr[1,])
expr <- expr[-1,]
rownames(expr) <- 1:nrow(expr)
```

```{r}
copy_y <- expr[2:ncol(expr)]

# compare each expression value to thres
for(i in 1:nrow(copy_y)){
  for (j in 1:ncol(copy_y)){
    if (copy_y[i, j] >= 5){
      copy_y[i, j] <- 1
    } else{
      copy_y[i, j] <- 0
    }
  }
}
str(copy_y)
# sum the rows
copy_y <- cbind("SUM"=rowSums(copy_y == "1"), copy_y)
copy_y <- cbind("miR"=expr[,1], copy_y)
rownames(copy_y) <- 1:nrow(copy_y)
nrow(copy_y) # 1918
```

```{r}
nc = MiRNANameConverter()
known_miR <- checkMiRNAName(nc, as.character(copy_y$miR)) # all known miR
length(known_miR) # 1918
```

```{r}
unique_miR <- length(unique(copy_y$miR)) # all unique, save all
copy_y <- cbind(copy_y[,1:2], "num_rep"=1)
copy_y <- cbind(copy_y, "sample_num"=200)
colnames(copy_y)[1] <- "miR"
colnames(copy_y)[2] <- "adipose.tissue"
copy_y <- copy_y[,-3]
write.table(copy_y, "/Users/helending/Documents/BCB330/mirDIP/expr_data_known/final_known_adipose_tissue.csv")
```