---
title: "R Notebook"
output: html_notebook
---

```{r}
setwd("/Users/helending/Documents/BCB330/code/disease_tissues/alzheimers_disease")
library(readxl)
```

```{r}
# Download dataset
datafile <- "GSE48552_normalized_counts.txt.gz"
if (!file.exists(datafile)) {
  datafile <- GEOquery::getGEOSuppFiles('GSE48552', makeDirectory = FALSE)
}

expr <- read.delim(datafile,header=TRUE,check.names=FALSE)
```
```{r}
copy_y <- expr[,8:ncol(expr)]

# compare each expression value to thres
for(i in 1:nrow(copy_y)){
  for (j in 1:ncol(copy_y)){
    if (copy_y[i, j] >= 5){
      copy_y[i, j] <- 1
    } else{
      copy_y[i, j] <- 0
    }
  }
}

# sum the rows
copy_y <- cbind("SUM"=rowSums(copy_y), copy_y)
copy_y <- cbind("miR"=expr[,1], copy_y)
rownames(copy_y) <- 1:nrow(copy_y)
nrow(copy_y)
```
```{r}
nc = MiRNANameConverter()
known_miR <- checkMiRNAName(nc, as.character(copy_y$miR)) # all known miR
```

```{r}
unique_miR <- length(unique(copy_y$miR)) # all unique, save all
copy_y <- cbind(copy_y[,1:2], "num_rep"=1)
copy_y <- cbind(copy_y, "sample_num"=6)
colnames(copy_y)[1] <- "miR"
colnames(copy_y)[2] <- "Alzheimer.s.disease"
copy_y <- copy_y[,-3]
write.table(copy_y, "/Users/helending/Documents/BCB330/mirDIP/expr_data_known/final_known_alzheimers_disease.csv")
```


